dist: xenial
language: generic
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce

before_script:
  - |
    if [[ "$TRAVIS_BRANCH" = master && -z "$TRAVIS_PULL_REQUEST_BRANCH" ]]; then
      export TAG_LATEST=1
    fi
  - >-
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

jobs:
  include:
    - stage: deploy
      name: sbt
      script:
        - ./build.sh pull ci-sbt
        - ./build.sh build ci-sbt
        - ./build.sh push ci-sbt
    - stage: deploy
      name: ubuntu-init
      script:
        - images=(ubuntu-init-{14.04,16.04,18.04} ubuntu-init-python-{14.04,16.04,18.04})
        - ./build.sh pull "${images[@]}"
        - ./build.sh build "${images[@]}"
        - ./build.sh push "${images[@]}"
    - stage: deploy
      name: squid
      script:
        - ./build.sh pull squid-ssl
        - ./build.sh build squid-ssl
        - ./build.sh push squid-ssl
